#File name:    hosts

#Description:  Application file inventory. Defines machine type abc node to deploy specific artifacts

#Defines machine type def node to upload metadata.

[abc-node]
# server1 ansible_host=<target machine for DU deployment> ansible_user=<Ansible user> ansible_connection=ssh
# server1 ansible_host=<your host name> ansible_user=<your unix user> ansible_connection=ssh

[def-node] 
# server2 ansible_host=<target machine for artifact upload> ansible_user=<Ansible user> ansible_connection=ssh
# server2 ansible_host=<host> ansible_user=<user> ansible_connection=ssh