---
- hosts: localhost
  remote_user: root
  tasks:   
  - name: Updating /etc/hosts

  - name: "Installing necessary packages"
    become: yes
    apt:
      pkg:
      - nfs-kernel-server
      - ntp 
      - openmpi-bin 
      - openmpi-common 
      - libopenmpi3 
      - libopenmpi-dev 
  
  # passwordless ssh
  - name: Setting up passwordless SSH on the {{ headnode }}
    openssh_keypair:
      path: "{{ ansible_facts['user_dir'] }}/.ssh/id_rsa"
  
  - name: Copying the SSH key to the authorized_keys file
    authorized_key:
      user: "{{ ansible_facts['user_id'] }}"
      state: present
      key: "{{ lookup('file', '{{ ansible_facts[''user_dir''] }}/.ssh/id_rsa.pub') }}"

  - name: ssh-copy-id to the headnode 
    shell: ansible-playbook -i 172.27.1.254 deploy_authorized_keys.yml --ask-pass


# setting up nfs 
  - name: Show mount options on the {{ ansible_host }}
    shell: showmount -e {{ ansible_host }}
  
  - name: Configure /etc/fstab
    lineinfile: 
          path: /etc/fstab
          line: "{{ ansible_host }}:/home /home nfs defaults 0 0 "
          state: present
          backup: yes 

  - name: Mount everything
  - command: mount -av

  
# ntp configuration 
  - name: Synching time with the {{ ansible_host }}. Replacing {{ debian_pool }}'s
    replace: 
          path: /etc/ntp.conf
          after: ''
          before: ''
          regexp: "server timehost.stolaf.edu"
          replace: 

          line: pool 0.debian.pool.ntp.org iburst
          state: present 
          backup: yes


# log out and back in for nfs mounting to happen?